# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  release:
    types: [ "published" ]
  workflow_dispatch:

jobs:
  build:
    name: .NET
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
      OUTPUT_PATH: output
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Cache NuGet
      uses: actions/cache@v4
      with:
        path: ${{ github.workspace }}/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('Directory.Packages.props') }} #hash of project files
        restore-keys: ${{ runner.os }}-nuget-
    - name: Restore dependencies
      run: dotnet restore
    - name: Build (Debug)
      run: dotnet build --no-restore
    - name: Test (Debug)
      run: dotnet test --no-build --verbosity normal
    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore
    - name: Pack (Release)
      run: dotnet pack --configuration Release --no-build --output ${{ env.OUTPUT_PATH }}
    - name: Publish to Nuget
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_KEY}}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json



 
